server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://C:\Users\skaru\Desktop\native-repo
        git:
#          uri: file://C:\Users\skaru\Desktop\git-local-repo
          uri: https://github.com/Namkyungyun/spring-cloud-config.git

